//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KingsOfSacredStar.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class HelpMenu {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HelpMenu() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KingsOfSacredStar.Properties.HelpMenu", typeof(HelpMenu).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Back ähnelt.
        /// </summary>
        internal static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You can place buildings by selecting them in the HUD. ähnelt.
        /// </summary>
        internal static string Building0 {
            get {
                return ResourceManager.GetString("Building0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die By pressing &quot;Q&quot; you can rotate them before placing. ähnelt.
        /// </summary>
        internal static string Building1 {
            get {
                return ResourceManager.GetString("Building1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Your units are tagged blue, ähnelt.
        /// </summary>
        internal static string Color0 {
            get {
                return ResourceManager.GetString("Color0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die the Enemy units are tagged red, ähnelt.
        /// </summary>
        internal static string Color1 {
            get {
                return ResourceManager.GetString("Color1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Global units are green. ähnelt.
        /// </summary>
        internal static string Color2 {
            get {
                return ResourceManager.GetString("Color2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Good luck while testing. ähnelt.
        /// </summary>
        internal static string GoodLuck {
            get {
                return ResourceManager.GetString("GoodLuck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Have Fun! ähnelt.
        /// </summary>
        internal static string HaveFun {
            get {
                return ResourceManager.GetString("HaveFun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You can select your hero like a unit ähnelt.
        /// </summary>
        internal static string Hero0 {
            get {
                return ResourceManager.GetString("Hero0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die or by clicking on &quot;Hero&quot; on the HUD. ähnelt.
        /// </summary>
        internal static string Hero1 {
            get {
                return ResourceManager.GetString("Hero1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die They are able to perform a Sword-Spin, heal nearby units, ähnelt.
        /// </summary>
        internal static string Hero2 {
            get {
                return ResourceManager.GetString("Hero2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die or send arrows if they have enough mana. ähnelt.
        /// </summary>
        internal static string Hero3 {
            get {
                return ResourceManager.GetString("Hero3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die To start you need to go to ähnelt.
        /// </summary>
        internal static string HowStart0 {
            get {
                return ResourceManager.GetString("HowStart0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &quot;Single Player&quot; -&gt; &quot;New Game&quot; ähnelt.
        /// </summary>
        internal static string HowStart1 {
            get {
                return ResourceManager.GetString("HowStart1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Your are able to acquire resources from mines ähnelt.
        /// </summary>
        internal static string Mines0 {
            get {
                return ResourceManager.GetString("Mines0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die after capturing them with your hero. ähnelt.
        /// </summary>
        internal static string Mines1 {
            get {
                return ResourceManager.GetString("Mines1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die By clicking on any place on the mini-map ähnelt.
        /// </summary>
        internal static string MiniMap0 {
            get {
                return ResourceManager.GetString("MiniMap0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die you can move the camera to that exact location. ähnelt.
        /// </summary>
        internal static string MiniMap1 {
            get {
                return ResourceManager.GetString("MiniMap1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Your are able to give selected units a target by right-clicking on the map. ähnelt.
        /// </summary>
        internal static string Move0 {
            get {
                return ResourceManager.GetString("Move0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Right-clicking an enemy orders them to attack. ähnelt.
        /// </summary>
        internal static string Move1 {
            get {
                return ResourceManager.GetString("Move1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Next ähnelt.
        /// </summary>
        internal static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Placeholder ähnelt.
        /// </summary>
        internal static string Placeholder {
            get {
                return ResourceManager.GetString("Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Previous ähnelt.
        /// </summary>
        internal static string Previous {
            get {
                return ResourceManager.GetString("Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Recruit units by clicking on recruit-menu, ähnelt.
        /// </summary>
        internal static string Recruiting0 {
            get {
                return ResourceManager.GetString("Recruiting0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die located  on the HUD and choose a unit. ähnelt.
        /// </summary>
        internal static string Recruiting1 {
            get {
                return ResourceManager.GetString("Recruiting1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die While owning half the mines, ähnelt.
        /// </summary>
        internal static string SacredStar0 {
            get {
                return ResourceManager.GetString("SacredStar0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die you&apos;re able to capture the SacredStar and get a buff. ähnelt.
        /// </summary>
        internal static string SacredStar1 {
            get {
                return ResourceManager.GetString("SacredStar1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You are able to move the camera by using the keys &quot;W&quot;, &quot;A&quot;, &quot;S&quot; or &quot;D&quot; ähnelt.
        /// </summary>
        internal static string Scrolling0 {
            get {
                return ResourceManager.GetString("Scrolling0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die using &quot;Ctrl&quot;, the Space key or by scrolling you can adjust the height. ähnelt.
        /// </summary>
        internal static string Scrolling1 {
            get {
                return ResourceManager.GetString("Scrolling1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Your are able to select a unit by left-clicking on it, ähnelt.
        /// </summary>
        internal static string Select0 {
            get {
                return ResourceManager.GetString("Select0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die multiple ones by pulling a rectangle over them ähnelt.
        /// </summary>
        internal static string Select1 {
            get {
                return ResourceManager.GetString("Select1", resourceCulture);
            }
        }
    }
}
